lemma = "a"
sitelenpona = [ "󱤀" ]

[categories]
semantic = [ "evoke" ]

[definitions]
en = "(emphasis/emotion interjection); ah, oh, haha, eh, um"
nl = "(klemtoon/emotie tussenwerpsel); ah, oh, haha, eh, um"
