lemma = "ala"
sitelenpona = [ "󱤂" ]

[categories]
semantic = [ "counting" ]

[definitions]
en = "not, nothing, no; 0; (negation); (yes-no question)"
nl = "niet, niets, nee; 0; (ontkenning); (ja-nee-vraag)"
