lemma = "anpa"
sitelenpona = [ "󱤅" ]

[categories]
semantic = [ "locating" ]

[definitions]
en = "bottom, underside; below; defeat, humble, lowly"
nl = "onderkant, beneden, laag; nederlaag, nederlaag, bescheiden"
