lemma = "awen"
sitelenpona = [ "󱤈" ]

[categories]
semantic = [ "state" ]

[definitions]
en = "stay, remain, wait; protect, save; to continue"
nl = "stand houden, wachten, blijven; beschermen, redden; doorgaan"
