lemma = "ike"
sitelenpona = [ "󱤍" ]

[categories]
semantic = [ "descriptions" ]

[definitions]
en = "bad, negative, unpleasant, cringe, complex, harmful, unneeded"
nl = "slecht, negatief, onaangenaam, moeilijk, schadelijk, onnodig"
