lemma = "ken"
sitelenpona = [ "󱤘" ]

[categories]
semantic = [ "state" ]

[definitions]
en = "can, may, ability; possible; allow, enable; to be able to"
nl = "kunnen, vermogen, mogen; mogelijk, toestaan; in staat zijn"
