lemma = "ku"
sitelenpona = [ "󱦈" ]

[categories]
semantic = [ "activity" ]

[definitions]
en = "to interact with Toki Pona Dictionary by Sonja Lang"
nl = "gebruik maken van Toki Pona Dictionary van Sonja Lang"
