lemma = "kule"
sitelenpona = [ "󱤞" ]

[categories]
semantic = [ "sight" ]

[definitions]
en = "color; aspect of sense, timbre, pitch, flavor, texture; queer"
nl = "kleur; zintuiglijk aspect, toon, klankkleur, smaak, textuur; queer"
