lemma = "kulupu"
sitelenpona = [ "󱤟" ]

[categories]
semantic = [ "people" ]

[definitions]
en = "group, community, company, collection, team"
nl = "groep, gemeenschap, organisatie, verzameling, team"
