lemma = "musi"
sitelenpona = [ "󱤻" ]

[categories]
semantic = [ "ideas" ]

[definitions]
en = "entertainment, fun, game, art, amusing, interesting"
nl = "vermaak, plezier, spel, kunst, lol, interessant"
