lemma = "o"
sitelenpona = [ "󱥄" ]

[categories]
semantic = [ "evoke" ]

[definitions]
en = "(vocative/imperative marker), must, ought, should, could, would"
nl = "(vocatief-/gebiedende wijsmarkering), moeten, zouden"
