lemma = "pona"
sitelenpona = [ "󱥔" ]

[categories]
semantic = [ "descriptions" ]

[definitions]
en = "good, positive, pleasant, simple, friendly, useful, peaceful, based"
nl = "goed, positief, aangenaam, eenvoudig, vriendelijk, vredig"
