lemma = "pu"
sitelenpona = [ "󱥕" ]

[categories]
semantic = [ "activity" ]

[definitions]
en = "to interact with Toki Pona: The Language of Good by Sonja Lang"
nl = "gebruik maken van Toki Pona: The Language of Good van Sonja Lang"
