lemma = "selo"
sitelenpona = [ "󱥘" ]

[categories]
semantic = [ "locating", "body" ]

[definitions]
en = "outer layer, skin, peel, shell, bark; boundary"
nl = "buitenste laag, huid, schil, schors; grens"
