lemma = "sewi"
sitelenpona = [ "󱥚" ]

[categories]
semantic = [ "locating", "ideas" ]

[definitions]
en = "up, top, above; divine, sacred, supernatural; awesome, inspiring"
nl = "boven, bovenkant; goddelijk, heilig, bovennatuurlijk; inspirerend"
