lemma = "su"
sitelenpona = [ "su" ]

[categories]
semantic = [ "activity" ]

[definitions]
en = "to interact with the illustrated story book series produced by Sonja Lang"
nl = "gebruik maken van de geïllustreerde serie boeken van Sonja Lang"
