lemma = "supa"
sitelenpona = [ "󱥥" ]

[categories]
semantic = [ "things" ]

[definitions]
en = "horizontal surface, bed, floor, table, platform, stage"
nl = "horizontaal oppervlak, bed, vloer, tafel, platform, podium"
