lemma = "tawa"
sitelenpona = [ "󱥩" ]

[categories]
semantic = [ "state" ]

[definitions]
en = "motion, walking, flight, travel; going to, for; from the perspective of"
nl = "beweging, lopen, reis; gaan naar, voor; vanuit het perspectief van"
